all:
  hosts:
    node1:
      ansible_host: 192.168.148.101
      ip: 192.168.148.101
      access_ip: 192.168.148.101
    node2:
      ansible_host: 192.168.148.102
      ip: 192.168.148.102
      access_ip: 192.168.148.102
    node3:
      ansible_host: 192.168.148.103
      ip: 192.168.148.103
      access_ip: 192.168.148.103
    node4:
      ansible_host: 192.168.148.104
      ip: 192.168.148.104
      access_ip: 192.168.148.104
  children:
    kube_control_plane:
      hosts:
        master1:
        master2:
        master3:
    kube_node:
      hosts:
        node1:
    etcd:
      hosts:
        master1:
        master2:
        master3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}